[[0.168798,{"lines":{"0":[["                                                                                                                                  ",{}]],"1":[["                                                                                                                                  ",{}]],"2":[["                                                                                                                                  ",{}]],"3":[["                                                                                                                                  ",{}]],"4":[["                                                                                                                                  ",{}]],"5":[["                                                                                                                                  ",{}]],"6":[["                                                                                                                                  ",{}]],"7":[["                                                                                                                                  ",{}]],"8":[["                                                                                                                                  ",{}]],"9":[["                                                                                                                                  ",{}]],"10":[["                                                                                                                                  ",{}]],"11":[["                                                                                                                                  ",{}]],"12":[["                                                                                                                                  ",{}]],"13":[["                                                                                                                                  ",{}]],"14":[["                                                                                                                                  ",{}]],"15":[["                                                                                                                                  ",{}]],"16":[["                                                                                                                                  ",{}]],"17":[["                                                                                                                                  ",{}]],"18":[["                                                                                                                                  ",{}]],"19":[["                                                                                                                                  ",{}]],"20":[["                                                                                                                                  ",{}]],"21":[["                                                                                                                                  ",{}]],"22":[["                                                                                                                                  ",{}]],"23":[["                                                                                                                                  ",{}]],"24":[["                                                                                                                                  ",{}]],"25":[["                                                                                                                                  ",{}]],"26":[["                                                                                                                                  ",{}]],"27":[["                                                                                                                                  ",{}]],"28":[["                                                                                                                                  ",{}]],"29":[["                                                                                                                                  ",{}]],"30":[["                                                                                                                                  ",{}]],"31":[["                                                                                                                                  ",{}]],"32":[["                                                                                                                                  ",{}]],"33":[["                                                                                                                                  ",{}]]},"cursor":{"x":0,"y":0,"visible":true}}],[0.032978,{"lines":{"0":[["➜  ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["                                                                                                     ",{}]]},"cursor":{"x":29}}],[0.000107,{}],[2.689954,{"lines":{"0":[["➜  ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["d                                                                                                    ",{}]]},"cursor":{"x":30}}],[0.15085,{"lines":{"0":[["➜  ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["dj                                                                                                   ",{}]]},"cursor":{"x":31}}],[0.424184,{"lines":{"0":[["➜  ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["dji                                                                                                  ",{}]]},"cursor":{"x":32}}],[0.135863,{"lines":{"0":[["➜  ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["djin                                                                                                 ",{}]]},"cursor":{"x":33}}],[0.159656,{"lines":{"0":[["➜  ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["djini                                                                                                ",{}]]},"cursor":{"x":34}}],[0.168355,{"lines":{"0":[["➜  ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["djinit                                                                                               ",{}]]},"cursor":{"x":35}}],[0.728068,{}],[0.013197,{"cursor":{"x":0,"y":1}}],[0.033476,{"lines":{"1":[["(VENV)",{}],["➜  ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["                                                                                               ",{}]]},"cursor":{"x":35}}],[3.1e-05,{}],[1.033438,{"lines":{"1":[["(VENV)",{}],["➜  ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["p                                                                                              ",{}]]},"cursor":{"x":36}}],[0.191738,{"lines":{"1":[["(VENV)",{}],["➜  ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["py                                                                                             ",{}]]},"cursor":{"x":37}}],[0.447968,{"lines":{"1":[["(VENV)",{}],["➜  ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["python install.py                                                                              ",{}]]},"cursor":{"x":52}}],[1.039881,{"cursor":{"x":0,"y":2}}],[0.000962,{}],[0.235451,{"lines":{"2":[["Traceback (most recent call last):                                                                                                ",{}]],"3":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"4":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"5":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]]},"cursor":{"y":6}}],[0.000282,{"lines":{"6":[["    utility.execute()                                                                                                             ",{}]],"7":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"8":[["    django.setup()                                                                                                                ",{}]],"9":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"10":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"11":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"12":[["    app_config.import_models(all_models)                                                                                          ",{}]],"13":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"14":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"15":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"16":[["n import_module                                                                                                                   ",{}]],"17":[["    __import__(name)                                                                                                              ",{}]],"18":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"19":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"20":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"21":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"22":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]]},"cursor":{"y":23}}],[0.23163,{"lines":{"23":[["Traceback (most recent call last):                                                                                                ",{}]],"24":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"25":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"26":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]]},"cursor":{"y":27}}],[0.000291,{"lines":{"0":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"1":[["    app_config.import_models(all_models)                                                                                          ",{}]],"2":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"3":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"4":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"5":[["n import_module                                                                                                                   ",{}]],"6":[["    __import__(name)                                                                                                              ",{}]],"7":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"8":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"9":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"10":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"11":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"12":[["Traceback (most recent call last):                                                                                                ",{}]],"13":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"14":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"15":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"16":[["    utility.execute()                                                                                                             ",{}]],"17":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"18":[["    django.setup()                                                                                                                ",{}]],"19":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"20":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"21":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"22":[["    app_config.import_models(all_models)                                                                                          ",{}]],"23":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"24":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"25":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"26":[["n import_module                                                                                                                   ",{}]],"27":[["    __import__(name)                                                                                                              ",{}]],"28":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"29":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"30":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"31":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"32":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]]},"cursor":{"y":33}}],[0.240181,{"lines":{"0":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"1":[["n import_module                                                                                                                   ",{}]],"2":[["    __import__(name)                                                                                                              ",{}]],"3":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"4":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"5":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"6":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"7":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"8":[["Traceback (most recent call last):                                                                                                ",{}]],"9":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"10":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"11":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"12":[["    utility.execute()                                                                                                             ",{}]],"13":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"14":[["    django.setup()                                                                                                                ",{}]],"15":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"16":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"17":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"18":[["    app_config.import_models(all_models)                                                                                          ",{}]],"19":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"20":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"21":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"22":[["n import_module                                                                                                                   ",{}]],"23":[["    __import__(name)                                                                                                              ",{}]],"24":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"25":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"26":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"27":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"28":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"29":[["Traceback (most recent call last):                                                                                                ",{}]],"30":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"31":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"32":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]]}}],[0.00032,{"lines":{"0":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"1":[["    app_config.import_models(all_models)                                                                                          ",{}]],"2":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"3":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"4":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"5":[["n import_module                                                                                                                   ",{}]],"6":[["    __import__(name)                                                                                                              ",{}]],"7":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"8":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"9":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"10":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"11":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"12":[["Traceback (most recent call last):                                                                                                ",{}]],"13":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"14":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"15":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"16":[["    utility.execute()                                                                                                             ",{}]],"17":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"18":[["    django.setup()                                                                                                                ",{}]],"19":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"20":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"21":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"22":[["    app_config.import_models(all_models)                                                                                          ",{}]],"23":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"24":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"25":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"26":[["n import_module                                                                                                                   ",{}]],"27":[["    __import__(name)                                                                                                              ",{}]],"28":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"29":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"30":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"31":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"32":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]]}}],[0.232975,{"lines":{"0":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"1":[["n import_module                                                                                                                   ",{}]],"2":[["    __import__(name)                                                                                                              ",{}]],"3":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"4":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"5":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"6":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"7":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"8":[["Traceback (most recent call last):                                                                                                ",{}]],"9":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"10":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"11":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"12":[["    utility.execute()                                                                                                             ",{}]],"13":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"14":[["    django.setup()                                                                                                                ",{}]],"15":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"16":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"17":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"18":[["    app_config.import_models(all_models)                                                                                          ",{}]],"19":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"20":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"21":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"22":[["n import_module                                                                                                                   ",{}]],"23":[["    __import__(name)                                                                                                              ",{}]],"24":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"25":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"26":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"27":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"28":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"29":[["Traceback (most recent call last):                                                                                                ",{}]],"30":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"31":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"32":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]]}}],[0.000295,{"lines":{"0":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"1":[["    app_config.import_models(all_models)                                                                                          ",{}]],"2":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"3":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"4":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"5":[["n import_module                                                                                                                   ",{}]],"6":[["    __import__(name)                                                                                                              ",{}]],"7":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"8":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"9":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"10":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"11":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"12":[["Traceback (most recent call last):                                                                                                ",{}]],"13":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"14":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"15":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"16":[["    utility.execute()                                                                                                             ",{}]],"17":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"18":[["    django.setup()                                                                                                                ",{}]],"19":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"20":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"21":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"22":[["    app_config.import_models(all_models)                                                                                          ",{}]],"23":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"24":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"25":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"26":[["n import_module                                                                                                                   ",{}]],"27":[["    __import__(name)                                                                                                              ",{}]],"28":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"29":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"30":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"31":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"32":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]]}}],[0.246088,{"lines":{"0":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"1":[["n import_module                                                                                                                   ",{}]],"2":[["    __import__(name)                                                                                                              ",{}]],"3":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"4":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"5":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"6":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"7":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"8":[["Traceback (most recent call last):                                                                                                ",{}]],"9":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"10":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"11":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"12":[["    utility.execute()                                                                                                             ",{}]],"13":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"14":[["    django.setup()                                                                                                                ",{}]],"15":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"16":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"17":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"18":[["    app_config.import_models(all_models)                                                                                          ",{}]],"19":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"20":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"21":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"22":[["n import_module                                                                                                                   ",{}]],"23":[["    __import__(name)                                                                                                              ",{}]],"24":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"25":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"26":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"27":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"28":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"29":[["Traceback (most recent call last):                                                                                                ",{}]],"30":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"31":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"32":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]]}}],[0.000603,{"lines":{"0":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"1":[["    app_config.import_models(all_models)                                                                                          ",{}]],"2":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"3":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"4":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"5":[["n import_module                                                                                                                   ",{}]],"6":[["    __import__(name)                                                                                                              ",{}]],"7":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"8":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"9":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"10":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"11":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"12":[["Traceback (most recent call last):                                                                                                ",{}]],"13":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"14":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"15":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"16":[["    utility.execute()                                                                                                             ",{}]],"17":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"18":[["    django.setup()                                                                                                                ",{}]],"19":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"20":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"21":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"22":[["    app_config.import_models(all_models)                                                                                          ",{}]],"23":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"24":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"25":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"26":[["n import_module                                                                                                                   ",{}]],"27":[["    __import__(name)                                                                                                              ",{}]],"28":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"29":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"30":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"31":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"32":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]]}}],[0.230697,{"lines":{"0":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"1":[["n import_module                                                                                                                   ",{}]],"2":[["    __import__(name)                                                                                                              ",{}]],"3":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"4":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"5":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"6":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"7":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"8":[["Traceback (most recent call last):                                                                                                ",{}]],"9":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"10":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"11":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"12":[["    utility.execute()                                                                                                             ",{}]],"13":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"14":[["    django.setup()                                                                                                                ",{}]],"15":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"16":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"17":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"18":[["    app_config.import_models(all_models)                                                                                          ",{}]],"19":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"20":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"21":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"22":[["n import_module                                                                                                                   ",{}]],"23":[["    __import__(name)                                                                                                              ",{}]],"24":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"25":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"26":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"27":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"28":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"29":[["Traceback (most recent call last):                                                                                                ",{}]],"30":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"31":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"32":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]]}}],[0.000287,{"lines":{"0":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"1":[["    app_config.import_models(all_models)                                                                                          ",{}]],"2":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"3":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"4":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"5":[["n import_module                                                                                                                   ",{}]],"6":[["    __import__(name)                                                                                                              ",{}]],"7":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"8":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"9":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"10":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"11":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"12":[["Traceback (most recent call last):                                                                                                ",{}]],"13":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"14":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"15":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"16":[["    utility.execute()                                                                                                             ",{}]],"17":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"18":[["    django.setup()                                                                                                                ",{}]],"19":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"20":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"21":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"22":[["    app_config.import_models(all_models)                                                                                          ",{}]],"23":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"24":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"25":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"26":[["n import_module                                                                                                                   ",{}]],"27":[["    __import__(name)                                                                                                              ",{}]],"28":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"29":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"30":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"31":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"32":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]]}}],[0.233549,{"lines":{"0":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"1":[["n import_module                                                                                                                   ",{}]],"2":[["    __import__(name)                                                                                                              ",{}]],"3":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"4":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"5":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"6":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"7":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"8":[["Traceback (most recent call last):                                                                                                ",{}]],"9":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"10":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"11":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"12":[["    utility.execute()                                                                                                             ",{}]],"13":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"14":[["    django.setup()                                                                                                                ",{}]],"15":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"16":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"17":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"18":[["    app_config.import_models(all_models)                                                                                          ",{}]],"19":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"20":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"21":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"22":[["n import_module                                                                                                                   ",{}]],"23":[["    __import__(name)                                                                                                              ",{}]],"24":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"25":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"26":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"27":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"28":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"29":[["Traceback (most recent call last):                                                                                                ",{}]],"30":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"31":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"32":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]]}}],[0.015634,{"lines":{"0":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"1":[["    app_config.import_models(all_models)                                                                                          ",{}]],"2":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"3":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"4":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"5":[["n import_module                                                                                                                   ",{}]],"6":[["    __import__(name)                                                                                                              ",{}]],"7":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"8":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"9":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"10":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"11":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"12":[["Traceback (most recent call last):                                                                                                ",{}]],"13":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"14":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"15":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"16":[["    utility.execute()                                                                                                             ",{}]],"17":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"18":[["    django.setup()                                                                                                                ",{}]],"19":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"20":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"21":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"22":[["    app_config.import_models(all_models)                                                                                          ",{}]],"23":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"24":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"25":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"26":[["n import_module                                                                                                                   ",{}]],"27":[["    __import__(name)                                                                                                              ",{}]],"28":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"29":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"30":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"31":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"32":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"33":[["Create super user?[Y/n]                                                                                                           ",{}]]},"cursor":{"x":24}}],[1.563004,{"lines":{"33":[["Create super user?[Y/n] ^C                                                                                                        ",{}]]},"cursor":{"x":26}}],[0.002383999999999999,{"lines":{"0":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"1":[["n import_module                                                                                                                   ",{}]],"2":[["    __import__(name)                                                                                                              ",{}]],"3":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"4":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"5":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"6":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"7":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"8":[["Traceback (most recent call last):                                                                                                ",{}]],"9":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"10":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"11":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"12":[["    utility.execute()                                                                                                             ",{}]],"13":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"14":[["    django.setup()                                                                                                                ",{}]],"15":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"16":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"17":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"18":[["    app_config.import_models(all_models)                                                                                          ",{}]],"19":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"20":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"21":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"22":[["n import_module                                                                                                                   ",{}]],"23":[["    __import__(name)                                                                                                              ",{}]],"24":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"25":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"26":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"27":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"28":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"29":[["Create super user?[Y/n] ^CTraceback (most recent call last):                                                                      ",{}]],"30":[["  File \"install.py\", line 46, in <module>                                                                                         ",{}]],"31":[["    ans = raw_input('Create super user?[Y/n] ')                                                                                   ",{}]],"32":[["KeyboardInterrupt                                                                                                                 ",{}]],"33":[["                                                                                                                                  ",{}]]},"cursor":{"x":0}}],[0.032299,{"lines":{"33":[["(VENV)",{}],["➜ ",{"fg":1,"bold":true}],[" ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["                                                                                               ",{}]]},"cursor":{"x":35}}],[3e-05,{}],[1.445228,{"lines":{"0":[["n import_module                                                                                                                   ",{}]],"1":[["    __import__(name)                                                                                                              ",{}]],"2":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"3":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"4":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"5":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"6":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"7":[["Traceback (most recent call last):                                                                                                ",{}]],"8":[["  File \"./manage.py\", line 10, in <module>                                                                                        ",{}]],"9":[["    execute_from_command_line(sys.argv)                                                                                           ",{}]],"10":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 385, in execute_from_command_line ",{}]],"11":[["    utility.execute()                                                                                                             ",{}]],"12":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute                   ",{}]],"13":[["    django.setup()                                                                                                                ",{}]],"14":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/__init__.py\", line 21, in setup                                      ",{}]],"15":[["    apps.populate(settings.INSTALLED_APPS)                                                                                        ",{}]],"16":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate                             ",{}]],"17":[["    app_config.import_models(all_models)                                                                                          ",{}]],"18":[["  File \"/Users/hydai/VENV/lib/python2.7/site-packages/django/apps/config.py\", line 202, in import_models                          ",{}]],"19":[["    self.models_module = import_module(models_module_name)                                                                        ",{}]],"20":[["  File \"/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py\", line 37, i",{}]],"21":[["n import_module                                                                                                                   ",{}]],"22":[["    __import__(name)                                                                                                              ",{}]],"23":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 121, in <module>                                      ",{}]],"24":[["    class SubmissionDetail(models.Model):                                                                                         ",{}]],"25":[["  File \"/Users/hydai/Program/NTHU_OJ/NTHUOJ_Master/problem/models.py\", line 141, in SubmissionDetail                              ",{}]],"26":[["    verdict = models.CharField(max_length=3, choices=VERDICT_CHOICE, default='')                                                  ",{}]],"27":[["NameError: name 'VERDICT_CHOICE' is not defined                                                                                   ",{}]],"28":[["Create super user?[Y/n] ^CTraceback (most recent call last):                                                                      ",{}]],"29":[["  File \"install.py\", line 46, in <module>                                                                                         ",{}]],"30":[["    ans = raw_input('Create super user?[Y/n] ')                                                                                   ",{}]],"31":[["KeyboardInterrupt                                                                                                                 ",{}]],"32":[["(VENV)",{}],["➜ ",{"fg":1,"bold":true}],[" ",{"fg":2,"bold":true}],["NTHUOJ_Master ",{"fg":6,"bold":true}],["git:(",{"fg":4,"bold":true}],["dev",{"fg":1,"bold":true}],[") ",{"fg":4,"bold":true}],["✗",{"fg":3,"bold":true}],[" ",{"fg":4,"bold":true}],["                                                                                               ",{}]],"33":[["                                                                                                                                  ",{}]]},"cursor":{"x":0}}]]